export const CLIENT_CONFIG = {
  MASTER_SPREADSHEET_ID: '1Sk2Z2eDbj-LRspGzIB4zg6X1ERNELdUz3TdWwEZEUa0',
  SERVER_LIBRARY_ID: 'AKfycbzjRwtPTCkHPy-D54w0ZDXgfctL89-FO82keskf5XFr81BUnETtDEFVTDEuXIwuuSRX',
  SERVER_LIBRARY_VERSION: 'HEAD',
  BATCH_SIZE: 50,
  MAX_CONCURRENT_BATCHES: 10,
  BATCH_TIMEOUT_MS: 30000,
} as const;